#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/env.php';

use Symfony\Component\Console\Application;
use Codevelopers\Fullstack\Console\HelloWorld;
use Codevelopers\Fullstack\Console\ThemeUpdate;
use Codevelopers\Fullstack\Console\PluginInstall;
use Codevelopers\Fullstack\Console\DatabaseCreate;
use Codevelopers\Fullstack\Console\DatabaseExport;
use Codevelopers\Fullstack\Console\DatabaseImport;

$application = new Application();

// ... register commands
$application->add(new HelloWorld());
$application->add(new DatabaseCreate());
$application->add(new DatabaseExport());
$application->add(new DatabaseImport());
$application->add(new ThemeUpdate());
$application->add(new PluginInstall());

$application->run();
